import json
import os
from typing import List, Optional
from models import ReportAnalysisOutput # Changed to absolute import

# Define the history directory relative to this file's location or a fixed path
HISTORY_DIR_NAME = "history_records"
# Construct path: assumes services/ is one level down from backend_root where history_records/ should be
BACKEND_ROOT_GUESS = os.path.abspath(os.path.join(os.path.dirname(__file__), '..')) # one level up from services/
HISTORY_DIR_PATH = os.path.join(BACKEND_ROOT_GUESS, HISTORY_DIR_NAME)
# Ensure this directory exists when the module is loaded, or at least when functions are called.
# For simplicity, functions will check/create.

def save_analysis(analysis_output: ReportAnalysisOutput, history_dir: str = HISTORY_DIR_PATH) -> None:
    """
    Saves a ReportAnalysisOutput object to a JSON file in the specified history directory.
    The filename is based on the report_id.
    """
    if not os.path.exists(history_dir):
        os.makedirs(history_dir, exist_ok=True)

    analysis_dict = analysis_output.to_dict()
    # Use report_id for filename, ensuring it's a string.
    # Report ID should be generated by the API endpoint before calling this.
    filename = f"analysis_{str(analysis_output.report_id)}.json"
    filepath = os.path.join(history_dir, filename)

    try:
        with open(filepath, 'w') as f:
            json.dump(analysis_dict, f, indent=4)
        print(f"Analysis for report ID {analysis_output.report_id} saved successfully to {filepath}")
    except IOError as e:
        print(f"Error saving analysis to {filepath}: {e}")
    except TypeError as e:
        print(f"Error serializing analysis to JSON for report ID {analysis_output.report_id}: {e}")

def load_analysis(report_id: str, history_dir: str = HISTORY_DIR_PATH) -> Optional[ReportAnalysisOutput]:
    """
    Loads a single ReportAnalysisOutput object from a JSON file based on the report_id.
    """
    filename = f"analysis_{str(report_id)}.json" # Ensure report_id is string for filename
    filepath = os.path.join(history_dir, filename)

    if not os.path.exists(filepath):
        print(f"History file not found for report ID {report_id} at {filepath}")
        return None

    try:
        with open(filepath, 'r') as f:
            data = json.load(f)
            # Pass the data directly to ReportAnalysisOutput.from_dict
            analysis_output = ReportAnalysisOutput.from_dict(data)
            print(f"Successfully loaded analysis for report ID {report_id} from {filepath}")
            return analysis_output
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON from {filepath} for report ID {report_id}: {e}")
    except IOError as e:
        print(f"Error reading file {filepath} for report ID {report_id}: {e}")
    except Exception as e:
        print(f"Error reconstructing ReportAnalysisOutput from {filepath} for report ID {report_id}: {e}")
    return None

def load_all_analyses(history_dir: str = HISTORY_DIR_PATH) -> List[ReportAnalysisOutput]:
    """
    Loads all ReportAnalysisOutput objects from JSON files in the specified history directory.
    """
    if not os.path.exists(history_dir):
        print(f"History directory '{history_dir}' not found.")
        return []

    analyses: List[ReportAnalysisOutput] = []
    for filename in os.listdir(history_dir):
        if filename.startswith("analysis_") and filename.endswith(".json"):
            # Extract report_id from filename, assuming format "analysis_{report_id}.json"
            report_id_from_filename = filename[len("analysis_"):-len(".json")]

            analysis_output = load_analysis(report_id_from_filename, history_dir)
            if analysis_output:
                 analyses.append(analysis_output)
            # load_analysis already prints errors for individual file load failures

    return analyses
